-- Generated by Oracle SQL Developer Data Modeler 21.4.1.349.1605
--   at:        2022-01-21 13:46:18 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE boravi_g (
    kontrolni_toranj_rbr_kt INTEGER NOT NULL,
    kon_let_mbr_r           INTEGER NOT NULL
);

CREATE UNIQUE INDEX boravi_g__idx ON
    boravi_g (
        kon_let_mbr_r
    ASC );

ALTER TABLE boravi_g ADD CONSTRAINT boravi_g_pk PRIMARY KEY ( kontrolni_toranj_rbr_kt,
                                                              kon_let_mbr_r );

CREATE TABLE drzava (
    ozn_d VARCHAR2(3 CHAR) NOT NULL
);

ALTER TABLE drzava ADD CONSTRAINT drzava_pk PRIMARY KEY ( ozn_d );

CREATE TABLE hangar (
    ozn_hg                VARCHAR2(12 CHAR) NOT NULL,
    br_av                 INTEGER NOT NULL,
    vojni_aerodrom_reg_va VARCHAR2(16 CHAR) NOT NULL,
    vojni_aerodrom_ozn_d  VARCHAR2(3 CHAR) NOT NULL
);

ALTER TABLE hangar ADD CONSTRAINT hangar_pk PRIMARY KEY ( ozn_hg );

CREATE TABLE hijerarhija (
    nadredjeni INTEGER NOT NULL,
    podredjeni INTEGER NOT NULL
);

ALTER TABLE hijerarhija ADD CONSTRAINT hijerarhija_pk PRIMARY KEY ( nadredjeni,
                                                                    podredjeni );

CREATE TABLE ima_g (
    model_vojnog_aviona_s_mod VARCHAR2(16 CHAR) NOT NULL,
    sistem_naoruzanja_sis_naz VARCHAR2(32 CHAR) NOT NULL,
    s_mod1                    VARCHAR2(16 CHAR),
    sis_naz1                  VARCHAR2(32 CHAR)
);

ALTER TABLE ima_g ADD CONSTRAINT ima_g_pk PRIMARY KEY ( model_vojnog_aviona_s_mod,
                                                        sistem_naoruzanja_sis_naz );

CREATE TABLE ima_p (
    vojni_aerodrom_reg_va     VARCHAR2(16 CHAR) NOT NULL,
    vojni_aerodrom_ozn_d      VARCHAR2(3 CHAR) NOT NULL,
    model_vojnog_aviona_s_mod VARCHAR2(16 CHAR) NOT NULL
);

ALTER TABLE ima_p
    ADD CONSTRAINT ima_p_pk PRIMARY KEY ( vojni_aerodrom_reg_va,
                                          vojni_aerodrom_ozn_d,
                                          model_vojnog_aviona_s_mod );

CREATE TABLE kon_let (
    mbr_r INTEGER NOT NULL
);

ALTER TABLE kon_let ADD CONSTRAINT kon_let_pk PRIMARY KEY ( mbr_r );

CREATE TABLE kont_letove (
    boravi_g_rbr_kt INTEGER NOT NULL,
    boravi_g_mbr_r  INTEGER NOT NULL,
    nalazi_g_reg_av VARCHAR2(16 CHAR) NOT NULL,
    nalazi_g_rbr_pi INTEGER NOT NULL
);

ALTER TABLE kont_letove
    ADD CONSTRAINT kon_letv1_pk PRIMARY KEY ( boravi_g_rbr_kt,
                                              boravi_g_mbr_r,
                                              nalazi_g_reg_av,
                                              nalazi_g_rbr_pi );

CREATE TABLE kontrolni_toranj (
    rbr_kt                INTEGER NOT NULL,
    br_klt                INTEGER NOT NULL,
    vojni_aerodrom_reg_va VARCHAR2(16 CHAR) NOT NULL,
    vojni_aerodrom_ozn_d  VARCHAR2(3 CHAR) NOT NULL
);

ALTER TABLE kontrolni_toranj ADD CONSTRAINT kontrolni_toranj_pk PRIMARY KEY ( rbr_kt );

CREATE TABLE leti_p (
    pilot_mbr_r     INTEGER NOT NULL,
    nalazi_g_reg_av VARCHAR2(16 CHAR) NOT NULL,
    nalazi_g_rbr_pi INTEGER NOT NULL
);

ALTER TABLE leti_p
    ADD CONSTRAINT leti_p_pk PRIMARY KEY ( pilot_mbr_r,
                                           nalazi_g_reg_av,
                                           nalazi_g_rbr_pi );

CREATE TABLE mehanicar (
    mbr_r INTEGER NOT NULL
);

ALTER TABLE mehanicar ADD CONSTRAINT mehanicar_pk PRIMARY KEY ( mbr_r );

CREATE TABLE model_vojnog_aviona (
    s_mod   VARCHAR2(16 CHAR) NOT NULL,
    naz_mod VARCHAR2(32 CHAR) NOT NULL,
    tip_mod VARCHAR2(16) NOT NULL
);

ALTER TABLE model_vojnog_aviona ADD CONSTRAINT model_vojnog_aviona_pk PRIMARY KEY ( s_mod );

CREATE TABLE nalazi_g (
    vojni_avion_reg_av VARCHAR2(16 CHAR) NOT NULL,
    pista_rbr_pi       INTEGER NOT NULL
);

CREATE UNIQUE INDEX nalazi_g__idx ON
    nalazi_g (
        vojni_avion_reg_av
    ASC );

ALTER TABLE nalazi_g ADD CONSTRAINT nalazi_g_pk PRIMARY KEY ( vojni_avion_reg_av,
                                                              pista_rbr_pi );

CREATE TABLE odrzava_p (
    mehanicar_mbr_r    INTEGER NOT NULL,
    skladisti_g_reg_av VARCHAR2(16 CHAR) NOT NULL,
    skladisti_g_ozn_hg VARCHAR2(12 CHAR) NOT NULL
);

ALTER TABLE odrzava_p
    ADD CONSTRAINT odrzava_p_pk PRIMARY KEY ( mehanicar_mbr_r,
                                              skladisti_g_reg_av,
                                              skladisti_g_ozn_hg );

CREATE TABLE pilot (
    mbr_r  INTEGER NOT NULL,
    br_sat INTEGER NOT NULL
);

ALTER TABLE pilot ADD CONSTRAINT pilot_pk PRIMARY KEY ( mbr_r );

CREATE TABLE pista (
    rbr_pi                INTEGER NOT NULL,
    br_av                 INTEGER NOT NULL,
    vojni_aerodrom_reg_va VARCHAR2(16 CHAR) NOT NULL,
    vojni_aerodrom_ozn_d  VARCHAR2(3 CHAR) NOT NULL
);

ALTER TABLE pista ADD CONSTRAINT pista_pk PRIMARY KEY ( rbr_pi );

CREATE TABLE zaposleni (
    mbr_r                 INTEGER NOT NULL,
    ime_r                 VARCHAR2(12 CHAR) NOT NULL,
    prz_r                 VARCHAR2(12 CHAR) NOT NULL,
    zan_r                 VARCHAR2(16) NOT NULL,
    dat_rr                VARCHAR2(16) NOT NULL,
    cin_r                 VARCHAR2(16 CHAR) NOT NULL,
    vojni_aerodrom_reg_va VARCHAR2(16 CHAR),
    vojni_aerodrom_ozn_d  VARCHAR2(3 CHAR)
);

ALTER TABLE zaposleni ADD CONSTRAINT zaposleni_pk PRIMARY KEY ( mbr_r );

CREATE TABLE sistem_naoruzanja (
    sis_naz VARCHAR2(32 CHAR) NOT NULL,
    br_rak  INTEGER NOT NULL,
    tip_rak VARCHAR2(16) NOT NULL
);

ALTER TABLE sistem_naoruzanja ADD CONSTRAINT sistem_naoruzanja_pk PRIMARY KEY ( sis_naz );

CREATE TABLE skladisti_g (
    vojni_avion_reg_av VARCHAR2(16 CHAR) NOT NULL,
    hangar_ozn_hg      VARCHAR2(12 CHAR) NOT NULL
);

CREATE UNIQUE INDEX skladisti_g__idx ON
    skladisti_g (
        vojni_avion_reg_av
    ASC );

ALTER TABLE skladisti_g ADD CONSTRAINT skladisti_g_pk PRIMARY KEY ( vojni_avion_reg_av,
                                                                    hangar_ozn_hg );

CREATE TABLE vojni_aerodrom (
    reg_va       VARCHAR2(16 CHAR) NOT NULL,
    naziv_va     VARCHAR2(32 CHAR) NOT NULL,
    lokacija     VARCHAR2(32 CHAR),
    br_zap       INTEGER NOT NULL,
    br_mav       INTEGER NOT NULL,
    br_kt        INTEGER NOT NULL,
    drzava_ozn_d VARCHAR2(3 CHAR) NOT NULL
);

ALTER TABLE vojni_aerodrom ADD CONSTRAINT vojni_aerodrom_pk PRIMARY KEY ( reg_va,
                                                                          drzava_ozn_d );

CREATE TABLE vojni_avion (
    reg_av        VARCHAR2(16 CHAR) NOT NULL,
    sis_av        VARCHAR2(16 CHAR) NOT NULL,
    br_sed        INTEGER NOT NULL,
    ima_g_s_mod   VARCHAR2(16 CHAR) NOT NULL,
    ima_g_sis_naz VARCHAR2(32 CHAR) NOT NULL
);

ALTER TABLE vojni_avion ADD CONSTRAINT vojni_avion_pk PRIMARY KEY ( reg_av );

ALTER TABLE boravi_g
    ADD CONSTRAINT boravi_g_kon_let_fk FOREIGN KEY ( kon_let_mbr_r )
        REFERENCES kon_let ( mbr_r );

ALTER TABLE boravi_g
    ADD CONSTRAINT boravi_g_kontrolni_toranj_fk FOREIGN KEY ( kontrolni_toranj_rbr_kt )
        REFERENCES kontrolni_toranj ( rbr_kt );

ALTER TABLE hangar
    ADD CONSTRAINT hangar_vojni_aerodrom_fk FOREIGN KEY ( vojni_aerodrom_reg_va,
                                                          vojni_aerodrom_ozn_d )
        REFERENCES vojni_aerodrom ( reg_va,
                                    drzava_ozn_d );

ALTER TABLE hijerarhija
    ADD CONSTRAINT hijerarhija_zaposleni_fk FOREIGN KEY ( nadredjeni )
        REFERENCES zaposleni ( mbr_r );

ALTER TABLE hijerarhija
    ADD CONSTRAINT hijerarhija_zaposleni_fkv1 FOREIGN KEY ( podredjeni )
        REFERENCES zaposleni ( mbr_r );

ALTER TABLE ima_g
    ADD CONSTRAINT ima_g_model_vojnog_aviona_fk FOREIGN KEY ( model_vojnog_aviona_s_mod )
        REFERENCES model_vojnog_aviona ( s_mod );

ALTER TABLE ima_g
    ADD CONSTRAINT ima_g_sistem_naoruzanja_fk FOREIGN KEY ( sistem_naoruzanja_sis_naz )
        REFERENCES sistem_naoruzanja ( sis_naz );

ALTER TABLE ima_p
    ADD CONSTRAINT ima_p_model_vojnog_aviona_fk FOREIGN KEY ( model_vojnog_aviona_s_mod )
        REFERENCES model_vojnog_aviona ( s_mod );

ALTER TABLE ima_p
    ADD CONSTRAINT ima_p_vojni_aerodrom_fk FOREIGN KEY ( vojni_aerodrom_reg_va,
                                                         vojni_aerodrom_ozn_d )
        REFERENCES vojni_aerodrom ( reg_va,
                                    drzava_ozn_d );

ALTER TABLE kon_let
    ADD CONSTRAINT kon_let_zaposleni_fk FOREIGN KEY ( mbr_r )
        REFERENCES zaposleni ( mbr_r );

ALTER TABLE kont_letove
    ADD CONSTRAINT kon_letv1_boravi_g_fk FOREIGN KEY ( boravi_g_rbr_kt,
                                                       boravi_g_mbr_r )
        REFERENCES boravi_g ( kontrolni_toranj_rbr_kt,
                              kon_let_mbr_r );

ALTER TABLE kont_letove
    ADD CONSTRAINT kon_letv1_nalazi_g_fk FOREIGN KEY ( nalazi_g_reg_av,
                                                       nalazi_g_rbr_pi )
        REFERENCES nalazi_g ( vojni_avion_reg_av,
                              pista_rbr_pi );

ALTER TABLE kontrolni_toranj
    ADD CONSTRAINT kon_tor_vojni_aerodrom_fk FOREIGN KEY ( vojni_aerodrom_reg_va,
                                                           vojni_aerodrom_ozn_d )
        REFERENCES vojni_aerodrom ( reg_va,
                                    drzava_ozn_d );

ALTER TABLE leti_p
    ADD CONSTRAINT leti_p_nalazi_g_fk FOREIGN KEY ( nalazi_g_reg_av,
                                                    nalazi_g_rbr_pi )
        REFERENCES nalazi_g ( vojni_avion_reg_av,
                              pista_rbr_pi );

ALTER TABLE leti_p
    ADD CONSTRAINT leti_p_pilot_fk FOREIGN KEY ( pilot_mbr_r )
        REFERENCES pilot ( mbr_r );

ALTER TABLE mehanicar
    ADD CONSTRAINT mehanicar_zaposleni_fk FOREIGN KEY ( mbr_r )
        REFERENCES zaposleni ( mbr_r );

ALTER TABLE nalazi_g
    ADD CONSTRAINT nalazi_g_pista_fk FOREIGN KEY ( pista_rbr_pi )
        REFERENCES pista ( rbr_pi );

ALTER TABLE nalazi_g
    ADD CONSTRAINT nalazi_g_vojni_avion_fk FOREIGN KEY ( vojni_avion_reg_av )
        REFERENCES vojni_avion ( reg_av );

ALTER TABLE odrzava_p
    ADD CONSTRAINT odrzava_p_mehanicar_fk FOREIGN KEY ( mehanicar_mbr_r )
        REFERENCES mehanicar ( mbr_r );

ALTER TABLE odrzava_p
    ADD CONSTRAINT odrzava_p_skladisti_g_fk FOREIGN KEY ( skladisti_g_reg_av,
                                                          skladisti_g_ozn_hg )
        REFERENCES skladisti_g ( vojni_avion_reg_av,
                                 hangar_ozn_hg );

ALTER TABLE pilot
    ADD CONSTRAINT pilot_zaposleni_fk FOREIGN KEY ( mbr_r )
        REFERENCES zaposleni ( mbr_r );

ALTER TABLE pista
    ADD CONSTRAINT pista_vojni_aerodrom_fk FOREIGN KEY ( vojni_aerodrom_reg_va,
                                                         vojni_aerodrom_ozn_d )
        REFERENCES vojni_aerodrom ( reg_va,
                                    drzava_ozn_d );

ALTER TABLE zaposleni
    ADD CONSTRAINT zaposleni_vojni_aerodrom_fk FOREIGN KEY ( vojni_aerodrom_reg_va,
                                                          vojni_aerodrom_ozn_d )
        REFERENCES vojni_aerodrom ( reg_va,
                                    drzava_ozn_d );

ALTER TABLE skladisti_g
    ADD CONSTRAINT skladisti_g_hangar_fk FOREIGN KEY ( hangar_ozn_hg )
        REFERENCES hangar ( ozn_hg );

ALTER TABLE skladisti_g
    ADD CONSTRAINT skladisti_g_vojni_avion_fk FOREIGN KEY ( vojni_avion_reg_av )
        REFERENCES vojni_avion ( reg_av );

ALTER TABLE vojni_aerodrom
    ADD CONSTRAINT vojni_aerodrom_drzava_fk FOREIGN KEY ( drzava_ozn_d )
        REFERENCES drzava ( ozn_d );

ALTER TABLE vojni_avion
    ADD CONSTRAINT vojni_avion_ima_g_fk FOREIGN KEY ( ima_g_s_mod,
                                                      ima_g_sis_naz )
        REFERENCES ima_g ( model_vojnog_aviona_s_mod,
                           sistem_naoruzanja_sis_naz );

CREATE OR REPLACE TRIGGER arc_fkarc_3_pilot BEFORE
    INSERT OR UPDATE OF mbr_r ON pilot
    FOR EACH ROW
DECLARE
    d INTEGER;
BEGIN
    SELECT
        a.mbr_r
    INTO d
    FROM
        zaposleni a
    WHERE
        a.mbr_r = :new.mbr_r;

    IF ( d IS NULL OR d <> 3 ) THEN
        raise_application_error(
                               -20223,
                               'FK Pilot_zaposleni_FK in Table Pilot violates Arc constraint on Table zaposleni - discriminator column MBR_R doesn''t have value 3'
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_3_kon_let BEFORE
    INSERT OR UPDATE OF mbr_r ON kon_let
    FOR EACH ROW
DECLARE
    d INTEGER;
BEGIN
    SELECT
        a.mbr_r
    INTO d
    FROM
        zaposleni a
    WHERE
        a.mbr_r = :new.mbr_r;

    IF ( d IS NULL OR d <> 1 ) THEN
        raise_application_error(
                               -20223,
                               'FK Kon_Let_zaposleni_FK in Table Kon_Let violates Arc constraint on Table zaposleni - discriminator column MBR_R doesn''t have value 1'
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/

CREATE OR REPLACE TRIGGER arc_fkarc_3_mehanicar BEFORE
    INSERT OR UPDATE OF mbr_r ON mehanicar
    FOR EACH ROW
DECLARE
    d INTEGER;
BEGIN
    SELECT
        a.mbr_r
    INTO d
    FROM
        zaposleni a
    WHERE
        a.mbr_r = :new.mbr_r;

    IF ( d IS NULL OR d <> 2 ) THEN
        raise_application_error(
                               -20223,
                               'FK Mehanicar_zaposleni_FK in Table Mehanicar violates Arc constraint on Table zaposleni - discriminator column MBR_R doesn''t have value 2'
        );
    END IF;

EXCEPTION
    WHEN no_data_found THEN
        NULL;
    WHEN OTHERS THEN
        RAISE;
END;
/


